spring.application.name=reservation
server.port=8002

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=reservation-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest


#mongo
spring.data.mongodb.uri=mongodb://root:root@localhost:27017/reservation?authSource=admin

#batch
spring.batch.job.enabled=false
# ?? ????? ??? ?? ??
spring.batch.jdbc.initialize-schema=always


spring.datasource.url=jdbc:mysql://k13a201.p.ssafy.io:3306/reservation_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update


spring.config.import=classpath:common-application.properties