networks:
  msa-net:
    external: true

services:
  board-service:
    build: .
    container_name: board-service
    ports:
      - "8001:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/board
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
    networks:
      - msa-net
