networks:
  msa-net:
    external: true

services:
  user-service:
    build: .
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
    depends_on:
      - mysql
    networks:
      - msa-net
