server.servlet.context-path=/api

# AWS S3 Configuration
cloud.aws.credentials.access-key=AKIAV3CB2W7TMG3C5ZPE
cloud.aws.credentials.secret-key=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
cloud.aws.s3.bucket=jellypaw-bucket
cloud.aws.region.static=ap-northeast-2

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB