services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - msa-net

  # Kafka (KRaft 모드 - Zookeeper 불필요)
  kafka:
    image: apache/kafka:3.8.1
    container_name: kafka
    environment:
      TZ: Asia/Seoul
      KAFKA_CLUSTER_ID: "abcdefghijklmnopqrstuv"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:29093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    ports:
      - "9092:9092"
    networks:
      - msa-net

  mongo:
    image: mongo:8
    container_name: reservation-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - msa-net   # ✅ 추가

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: jellypaw-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TZ=Asia/Seoul
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - msa-net
    entrypoint:
      - bash
      - -c
      - |
        if [ ! -f /usr/share/elasticsearch/plugins/analysis-nori/.installed ]; then
          bin/elasticsearch-plugin install -b analysis-nori
          touch /usr/share/elasticsearch/plugins/analysis-nori/.installed
        fi
        /usr/local/bin/docker-entrypoint.sh eswrapper
    healthcheck:
      test:
        [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
  elasticsearch_data:

networks:
  msa-net:
    external: true