networks:
  msa-net:
    name: msa-net
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - msa-net

volumes:
  mysql_data:
