networks:
  msa-net:
    name: msa-net
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - msa-net

  # Kafka (KRaft 모드 - Zookeeper 불필요)
  kafka:
    image: apache/kafka:3.8.1
    container_name: jellypaw-kafka
    environment:
      TZ: Asia/Seoul
    ports:
      - "9092:9092"
    #networks:
    # - jellypaw-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: jellypaw-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TZ=Asia/Seoul
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - msa-net
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
  elasticsearch_data:
